### ISSUE TITLE
move, remove generate erors or silent failed

### ISSUE THREAD

**Issue by aplib** [michael/github#96] opened 2013-12-08 19:04 UTC
```var github = new window.github_api({
    username: "aplib",
    password: "xxx",
    auth: "basic"
});
var repo = github.getRepo('aplib', 'tmp');
repo.remove('gh-pages', '1/1.dat', function(err) {
    if (err) console.log(err);
});```

it's not worked. no error messages, no remove file.
in repo only folder '1' and file '1/1.dat'.

**Comment by aendrew** [comment] 2015-04-06 05:26
Duplicate of #108.

**Closed by aendrew** 2015-04-06 05:26 UTC
