### ISSUE TITLE
Github undefined

### ISSUE THREAD

**Issue by lucusp** [michael/github#247] opened 2015-10-24 23:55 UTC
I had been successfully deploying this on a website and now I keep getting github undefined. Worked earlier yesterday and I changed nothing. Anyone else with this issue? I apologize if this is not the appropriate place.

**Comment by aendrew** [comment] 2015-10-25 00:38
@lucusp Interesting; I changed the UMD code early last week, that might've done it. That said, the tests should have caught it if there's a problem.

Two questions —

1. Are you consuming Github.js via AMD (Require.js et al), CommonJS (Node.js et cetera) or browser global?

2. What version are you running? Could you try updating it to the latest commit on the master branch? We're wanting to release 0.10.7 within the next week or so, but the current version on NPM et al is really old.

Thanks!

**Comment by lucusp** [comment] 2015-10-25 01:44
Using the latest via browser global. Thanks for the quick response!!

**Comment by lucusp** [comment] 2015-10-25 01:45
FWIW it broke in my fork as well from a couple weeks ago.

**Comment by lucusp** [comment] 2015-10-25 01:46
Sorry meant to say that the had not modified the fork either.

**Comment by sebastiaanfranken** [comment] 2015-10-26 01:34
I'm having the same issue. I've taken the github.js from the repo verbatim and included it in my HTML file, updated the code to match and I too am getting "Github is undefined" warnings in the Chrome dev console.

So, to answer your two questions:

1: No, I am not consuming it through AMD/CommonJS. I'm running it in the browser, globally
2: The latest (I think). I pulled it out of the master branch a few minutes ago.

**Comment by HarrisCarney** [comment] 2015-10-26 01:39
Same issues here using browser global and latest. I'd have to agree that it's an issue with the umd boilerplate implementation.

**Comment by HarrisCarney** [comment] 2015-10-26 02:26
I suppose a simple fix (for browser global usage) would be to replace the return statement at the end of the file with window.Github = Github;

**Comment by aendrew** [comment] 2015-10-26 09:44
Hmm, has to be the UMD implementation. Sorry 'bout that folks, will take a look this morning.

**Comment by sebastiaanfranken** [comment] 2015-10-26 11:49
@aendrew The fix @HarrisCarney provided worked for me. I'm not sure if it breaks anything else though, since I'm running it witouth AMD or RequireJS. @HarrisCarney  should make a pull request :+1:

**Comment by aendrew** [comment] 2015-10-26 11:50
Could you all please try the commit I just checked into master? Should at least not throw undefined now.

This is really related to #149; we need to get some browser-based testing rolling, which simply isn't possible given the tests are written in Tape.

**Comment by sebastiaanfranken** [comment] 2015-10-26 11:57
Your latest commit fixed the issue for me, it works as intended

**Comment by aendrew** [comment] 2015-10-26 12:02
@sebastiaanfranken Hoorah! Thanks for reporting back! Hopefully it didn't break AMD and NodeJS! :sweat_smile: UMDs really aren't my strong suit...

**Comment by sebastiaanfranken** [comment] 2015-10-26 12:04
No problem! This level of JS coding is way above my skills, so I'm happy to help. Let's hope AMD/Node users can also use this, good luck with that

**Comment by aendrew** [comment] 2015-10-26 12:20
Closing for now...

**Closed by aendrew** 2015-10-26 12:20 UTC
Labels: bug

**Comment by lucusp** [comment] 2015-10-26 13:50
@aendrew thanks for getting to this so quickly!!
