### ISSUE TITLE
Is there any way for anonymous user get public repos list of some user?

### ISSUE THREAD

**Issue by SilentImp** [michael/github#32] opened 2013-01-05 16:32 UTC
Is there any way for anonymous user get public repos list of some user?
Why do you need github user if you want only read content of public repository?

**Comment by aendrew** [comment] 2015-10-17 01:58
Closing as a duplicate of #187 — if you can do it, it's not documented, and it's thus a documentation issue. If you can't in fact do it (I know, it's hysterical I'm the current maintainer and I don't know whether you can or not... :sweat_smile:), I'll make sure that is possible in 0.10.8.

**Closed by aendrew** 2015-10-17 01:58 UTC
