### ISSUE TITLE
repo.write throws "Update is not a fast forward" after first successful create

### ISSUE THREAD

**Issue by thebigspoon** [michael/github#78] opened 2013-09-27 19:41 UTC
Using the example from the docs, I can successfully write to my repo.

```javascript
// example write
repo.write('master', 'path/to/file', 'YOUR_NEW_CONTENTS', 'YOUR_COMMIT_MESSAGE', function(err) {});
```
 But only the first save seems to work. The others return a 422 status with the following error. I did notice [this prose ticket](https://github.com/prose/prose/issues/91)...wondering what the workaround there was?

```javascript
{
  "message": "Update is not a fast forward",
  "documentation_url": "http://developer.github.com/v3"
}
```

**Comment by aendrew** [comment] 2015-03-22 21:58
How are you doing callbacks? If you have something like

```
repo.write('master', 'hurr.txt', 'YAY!', 'Initial', function(err){});
repo.write('master', 'yay.txt', 'HURR!', 'Second', function(err){});
```

It will fail because both write calls will be against the same SHA, meaning one will succeed and the other will fail. 

Could you try a pattern more like:
```
repo.write('master', 'hurr.txt', 'YAY!', 'Initial', function(err){
  repo.write('master', 'hurr.txt', 'YAY!', 'Initial', function(err){
    console.log('donezo');
  });
});
```

...With the latest version of the library? Thanks!

**Comment by aendrew** [comment] 2015-10-17 01:40
Closing as duplicate of #85.

**Closed by aendrew** 2015-10-17 01:40 UTC
