### ISSUE TITLE
constructed with user/pass results in "TypeError: Cannot call method 'encode' of undefined"

### ISSUE THREAD

**Issue by Pomax** [michael/github#83] opened 2013-10-30 02:12 UTC
used as a pure client side version (no nodejs):

```
var github = new Github({
  username: "Pomax",
  password: "......"
});
var repo = github.getRepo("Pomax", "bezierinfo");
repo.getTree("masster", function(err, data) { console.log(data); });
```

which gives me

```
TypeError: Cannot call method 'encode' of undefined
```

If there is something missing from this sequence of calls, the readme.md will need the additional information added, otherwise this is probably a bug.

**Comment by aendrew** [comment] 2015-10-17 01:43
Marking as low priority bug for 0.10.7.

**Comment by aendrew** [comment] 2015-10-17 01:44
@mattpass Did you get anywhere with tracking that down?

**Comment by mattpass** [comment] 2015-10-17 16:22
@aendrew No, only tracked down circumstances under which it could be reproduced.

**Comment by Pomax** [comment] 2015-10-19 16:34
note: pomax.github.io moved to a different git interface, so the demonstration links in previous comments are no longer valid.

**Comment by aendrew** [comment] 2015-10-27 13:13
I think this is closed now — I tried the sample code and tested it in the browser with Karma, can't reproduce. 

If anyone comes across this again, please comment with a working test case and I'll reopen. Thanks!

**Closed by aendrew** 2015-10-27 13:13 UTC
Labels: bug, priority 4 (low), PRs welcome

**Comment by daconex** [comment] 2016-02-15 21:50
I'm having the same issue as @Pomax. 

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/github-api/dist/github.min.js"></script>
    <script src="js/main.js"></script>
</body>
</html>
```

main.js
```
var github = new Github({
    username: "<username>",
    password: "<password>",
    auth: "basic"
});

var user = github.getUser();

user.orgs(function(err, orgs) {
    console.log(orgs);
});
```

Here's a screenshot of the error in Chrome Version 48.0.2564.109 m (latest version).
![2016-02-15 16_46_27-settings](https://cloud.githubusercontent.com/assets/5752872/13061137/e713a172-d403-11e5-897c-ef1f9b2c2b8a.png)

**Comment by Pomax** [comment] 2016-02-15 22:58
slightly different issue - I was using this purely server-side, because if you're putting in a username and password client-side you've just given the world your github login.

**Comment by AurelioDeRosa** [comment] 2016-02-15 23:04
If you don't want to use a module loading system, you have  to use the `dist/github.bundle.min.js` file.

**Comment by daconex** [comment] 2016-02-16 05:13
Switching to `dist/github.bundle.min.js` fixed my issue. Thanks @AurelioDeRosa :smile:

**Comment by Pomax** [comment] 2016-02-16 05:53
just remember to never expose that username and password combination. Github's API tokens are a far safer authentication when using it client-side.

**Comment by daconex** [comment] 2016-02-16 06:03
@Pomax Good idea! I would never even consider using username and password on a release version of an application, but since finding this library, I'm considering making a second account to use as a "bot" from which I can make Github API requests from a client browser (using token oauth of course)!

**Comment by Pomax** [comment] 2016-02-16 16:59
I kept things single account, but I have a small express server running on cheap shell host that only my sites can talk to (CORS/access whitelisting), which then does the talking to github for only the repos a site should be able to talk to. The client has a simple plain JS "same API but no authentication", and the server is essentially an authenticated proxy.
