### ISSUE TITLE
Bug with Repo.write() in 0.10

### ISSUE THREAD

**Issue by nicolas-van** [michael/github#167] opened 2015-03-20 12:23 UTC
I reproduced the following bug with version 0.10.2 and 0.10.3 but it worked fine in 0.9.2 (all under Chrome 40).

Here is the code:

    var github = new Github({
        username: "nicolas-van",
        password: 'thepassword',
        auth: "basic",
    });

    var repo = github.getRepo("nicolas-van", "githubapitest");
    repo.write("gh-pages", "test.html", 'hello', '', function(err, res) {
        debugger;
    });

This code works fine if test.html doesn't exist yet, but crashes with a strange error if it already exists:

     Uncaught SyntaxError: Unexpected token e

I must precise that, in my test, `test.html` is a simple text file containing the word "test".

Bu debugging a little I also saw that it's not really the method `write()` that causes problem but the method `getSha()` (which is called at the beginning of the `write()` method).

**Comment by aendrew** [comment] 2015-03-20 15:48
Howdy!

I think this is a duplicate of #147. Luckily, I've just fixed it and it's been merged into master. Could you try using commit 7fc0ca0c72632cbd633b604c1f72ce1f74f8e9a8 for the moment? I'll probably try to do a new release in the next few days.

If that doesn't solve it for you, please report back and I'll reopen. Thanks!

**Closed by aendrew** 2015-03-20 15:48 UTC

**Comment by ingalls** [comment] 2015-03-20 17:03
@nicolas-van I've also pushed the fix to [npm](https://www.npmjs.com/package/github-api) as of v0.10.4

**Comment by nicolas-van** [comment] 2015-03-21 09:10
OK, I confirm it works correctly with that fix and in version 0.10.4 .

Thanks for the quick reply!

**Comment by aendrew** [comment] 2015-03-21 16:58
@ingalls Nice one, thanks for doing that! :+1:
