### ISSUE TITLE
Got TypeError: axios is not a function

### ISSUE THREAD

**Issue by JimmyLv** [michael/github#294] opened 2016-02-24 12:36 UTC
When I using it in Angular 1.5.x I got this error below:

```js
TypeError: axios is not a function
    at _request (github.js:77)
    at read (github.js:716)
    at $routeProvider.when.when.when.when.when.resolve.site (app.routes.js:87)
    at Object.invoke (angular.js:4604)
    at angular-route.js:614
    at Object.forEach (angular.js:335)
    at angular-route.js:612
    at processQueue (angular.js:15552)
    at angular.js:15568
    at Scope.$eval (angular.js:16820)
```

**Comment by AurelioDeRosa** [comment] 2016-02-24 14:35
We need more details.  How are you including the library? npm or Bower? How are you using it?

**Comment by Jack-Collins** [comment] 2016-02-25 21:41
Hi, I just started trying to work with this library today and I too have a "axios is not a function" error... I am loading jquery and angular -  are there any more dependencies?

**Comment by Jack-Collins** [comment] 2016-02-25 22:03
Rolled back to a previous version and this error is not present FYI

**Comment by AurelioDeRosa** [comment] 2016-02-25 22:28
There a few dependencies that you probably haven't loaded. This seems a duplicate of https://github.com/michael/github/issues/285#issuecomment-180782156

**Closed by AurelioDeRosa** 2016-02-25 22:28 UTC
Labels: needs clarification
