### ISSUE TITLE
getting specific branch content is not working

### ISSUE THREAD

**Issue by yonida** [michael/github#210] opened 2015-08-10 09:02 UTC
When using `.contents` with a specific branch name it always retrieves that master branch content.
The problem here is that ref should be a request parameter, for example:
`https://api.github.com/repos/:owner/:repo/contents/:path?ref=branch-nane`

In the code ref is an object and used as `xhr.send(JSON.stringify(data))` - which doesn't work.

**Comment by mushishi78** [comment] 2015-08-13 22:42
+1

**Comment by mushishi78** [comment] 2015-08-14 14:52
Oh I see this was fixed with [this commit](https://github.com/michael/github/commit/4daae44ad6dc37548cbadb65898241d87da8b05d).

**Comment by yonida** [comment] 2015-08-14 15:45
Using `this.read` can be a working alternative, but `this.contents` is still flawed

**Comment by mushishi78** [comment] 2015-08-14 16:16
Oh okay, but if you switch to the master branch, it really is fixed. I think it might be with [this commit](https://github.com/firehist/github/commit/8e9a513a3f714664252149617d37781bc969092f) then.

**Comment by yonida** [comment] 2015-08-14 16:30
Strange, i'm working on the master branch and I didn't get this code, just installed and got this:

```
function _request(method, path, data, cb, raw, sync) {
       function getURL() {
        var url = path.indexOf('//') >= 0 ? path : API_URL + path;
        return url + ((/\?/).test(url) ? '&' : '?') + (new Date()).getTime();
      }

      var xhr = new XMLHttpRequest();

**Comment by BenRKarl** [comment] 2015-09-01 16:43
:+1: Any idea when the release will be updated or if a new release is coming?

**Comment by aendrew** [comment] 2015-10-17 01:20
New release is really overdue, apologies for that. Will close this issue once I release 0.10.7.

**Comment by aendrew** [comment] 2015-10-17 01:20
Actually, marking as duplicate of #224. Please monitor that issue instead, thanks!

**Closed by aendrew** 2015-10-17 01:20 UTC
